import Room from "./Room"

export const Rooms: Room.Properties[] = [
  {
    name: "Panic Room",
    doors: [false, true, false, false],
    effects: [Room.Effect.Optional.MoveToDumbwaiterRoom],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Creaky Hallway",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.None,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Dusty Hallway",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.None,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Game Room",
    doors: [true, false, true, true],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Junk Room",
    doors: [true, true, true, true],
    effects: [Room.Effect.Required.LoseSpeed],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Mystic Elevator",
    doors: [true, false, false, false],
    effects: [Room.Effect.Optional.MoveToOpenDoor],
    card: Room.Card.None,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Organ Room",
    doors: [false, true, true, false],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Statuary Corridor",
    doors: [true, false, true, false],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Spiral Staircase",
    doors: [true, true, true, true],
    effects: [Room.Effect.Optional.MoveToAnyLanding],
    card: Room.Card.None,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Study",
    doors: [false, false, true, true],
    effects: [Room.Effect.Automatic.GainMental],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: true,
  },
  {
    name: "Locked Room",
    doors: [true, false, true, true],
    effects: [Room.Effect.Automatic.LockedDoor],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Drawing Room",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.Any,
    outside: false,
    windows: true,
    dumbwaiter: true,
  },
  {
    name: "Nursery",
    doors: [true, false, false, true],
    effects: [Room.Effect.Automatic.GainOrLoseSanity],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Sewing Room",
    doors: [true, true, true, true],
    effects: [Room.Effect.Optional.GainPhysical],
    card: Room.Card.Item,
    outside: false,
    windows: true,
    dumbwaiter: true,
  },
  {
    name: "Solarium",
    doors: [true, false, false, false],
    effects: [Room.Effect.Optional.GainSanity],
    card: Room.Card.Item,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Widow's Walk",
    doors: [false, true, true, true],
    effects: [Room.Effect.Automatic.AddKnowledgeAndSubtractSpeed],
    card: Room.Card.Event,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Rookery",
    doors: [false, true, false, true],
    effects: [Room.Effect.Required.PlaceRoom],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Gymnasium",
    doors: [false, false, true, true],
    effects: [Room.Effect.Automatic.GainSpeed],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Operating Laboratory",
    doors: [false, false, true, true],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Research Laboratory",
    doors: [true, false, true, false],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Servants' Quarters",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Storeroom",
    doors: [true, false, false, false],
    effects: [],
    card: Room.Card.Item,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Vault",
    doors: [true, false, false, false],
    effects: [Room.Effect.Optional.OpenVault],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Attic",
    doors: [false, false, true, false],
    effects: [Room.Effect.Required.LoseMight],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Balcony",
    doors: [true, false, true, false],
    effects: [],
    card: Room.Card.Omen,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Bedroom",
    doors: [false, true, false, true],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: true,
    dumbwaiter: false,
  },
  {
    name: "Gallery",
    doors: [true, false, true, false],
    effects: [Room.Effect.Optional.FallToBallroom],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Master Bedroom",
    doors: [true, true, false, false],
    effects: [],
    card: Room.Card.Omen,
    outside: false,
    windows: true,
    dumbwaiter: false,
  },
  {
    name: "Tower",
    doors: [false, true, false, true],
    effects: [Room.Effect.Optional.MightBarrier],
    card: Room.Card.Event,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Bathroom",
    doors: [false, false, true, false],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Bloody Room",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.Item,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Chapel",
    doors: [true, false, false, false],
    effects: [Room.Effect.Automatic.GainSanity],
    card: Room.Card.Event,
    outside: false,
    windows: true,
    dumbwaiter: false,
  },
  {
    name: "Charred Room",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Collapsed Room",
    doors: [true, true, true, true],
    effects: [Room.Effect.Required.FallToBasementAndPhysicalDamage],
    card: Room.Card.None,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Conservatory",
    doors: [true, false, false, false],
    effects: [],
    card: Room.Card.Event,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Library",
    doors: [false, true, true, false],
    effects: [Room.Effect.Automatic.GainKnowledge],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Theater",
    doors: [false, true, false, true],
    effects: [],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Ballroom",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Coal Chute",
    doors: [true, false, false, false],
    effects: [Room.Effect.Automatic.FallToBasement],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Dining Room",
    doors: [true, false, false, true],
    effects: [],
    card: Room.Card.Omen,
    outside: false,
    windows: true,
    dumbwaiter: false,
  },
  {
    name: "Gardens",
    doors: [true, false, true, false],
    effects: [],
    card: Room.Card.Event,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Graveyard",
    doors: [false, false, true, false],
    effects: [Room.Effect.Required.LoseKnowledge],
    card: Room.Card.Event,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Patio",
    doors: [true, true, true, false],
    effects: [],
    card: Room.Card.Event,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Tree House",
    doors: [false, true, true, false],
    effects: [Room.Effect.Required.PortalToUpperOrRoof],
    card: Room.Card.Event,
    outside: true,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Abandoned Room",
    doors: [true, true, true, true],
    effects: [],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Abandoned Room",
    doors: [false, false, true, true],
    effects: [Room.Effect.Automatic.DrawTwoItemsAndKeepOne],
    card: Room.Card.Item,
    outside: false,
    windows: false,
    dumbwaiter: true,
  },
  {
    name: "Kitchen",
    doors: [true, false, false, true],
    effects: [],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Laundry",
    doors: [false, true, true, false],
    effects: [Room.Effect.Optional.ChangeItem],
    card: Room.Card.Item,
    outside: false,
    windows: false,
    dumbwaiter: true,
  },
  {
    name: "Mevagerie",
    doors: [false, true, false, true],
    effects: [Room.Effect.Automatic.GainPhysical],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: true,
  },
  {
    name: "Catacombs",
    doors: [true, false, true, false],
    effects: [Room.Effect.Optional.SanityBarrier],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Cave",
    doors: [true, true, true, true],
    effects: [Room.Effect.Automatic.PhysicalDamage],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Chasm",
    doors: [false, true, false, true],
    effects: [Room.Effect.Optional.SpeedBarrier],
    card: Room.Card.None,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Crypt",
    doors: [true, false, false, false],
    effects: [Room.Effect.Automatic.LoseMental],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Dungeon",
    doors: [true, false, true, false],
    effects: [Room.Effect.Required.LoseSanityEnter],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Furnance Room",
    doors: [true, true, true, false],
    effects: [Room.Effect.Automatic.LosePhisycal],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Larder",
    doors: [true, false, true, false],
    effects: [Room.Effect.Automatic.GainMight],
    card: Room.Card.Item,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Pentagram Chamber",
    doors: [false, false, false, true],
    effects: [Room.Effect.Required.LoseSanityExit],
    card: Room.Card.Omen,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Stairs from Basement",
    doors: [true, false, true, false],
    effects: [],
    card: Room.Card.None,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Storm Cellar",
    doors: [false, false, true, true],
    effects: [],
    card: Room.Card.Item,
    outside: false,
    windows: false,
    dumbwaiter: true,
  },
  {
    name: "Underground Lake",
    doors: [true, false, false, true],
    effects: [],
    card: Room.Card.Event,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
  {
    name: "Wine Cellar",
    doors: [true, false, true, false],
    effects: [],
    card: Room.Card.Item,
    outside: false,
    windows: false,
    dumbwaiter: false,
  },
];
